from __future__ import annotations

APP_TITLE = "Disk Manager"
DEFAULT_PATH = "C:/"
MAX_VISIBLE_ROWS = 10000

LANG_EN = "en"
LANG_JA = "ja"

TEXT = {
    LANG_EN: {
        "title": "Disk Manager",
        "path": "Path",
        "browse": "Browse",
        "scan": "Scan",
        "stop": "Stop",
        "search": "Search",
        "sort_by": "Sort by",
        "language": "日本語",
        "quick_mode": "Quick mode",
        "status_ready": "Ready",
        "status_scanning": "Scanning files first, folder sizes in background...",
        "status_stopped": "Stopped",
        "status_done": "Done",
        "name": "Name",
        "type": "Type",
        "size": "Size",
        "modified": "Modified",
        "category": "Category",
        "full_path": "Full path",
        "file": "File",
        "folder": "Folder",
        "calculating": "calculating...",
        "error_path": "Path does not exist.",
        "select_folder": "Select folder",
        "all_disk_hint": "Use C:/ or another drive root to scan a whole disk.",
        "system": "System",
        "launcher": "Launcher",
        "game": "Game",
        "cache": "Cache / temporary",
        "user_files": "User files",
        "app_data": "Application data",
        "development": "Development",
        "media": "Media",
        "documents": "Documents",
        "archives": "Archives",
        "installers": "Installers",
        "programs": "Programs / executables",
        "other": "Other",
    },
    LANG_JA: {
        "title": "ディスクマネージャー",
        "path": "パス",
        "browse": "参照",
        "scan": "スキャン",
        "stop": "停止",
        "search": "検索",
        "sort_by": "並び替え",
        "language": "English",
        "quick_mode": "高速モード",
        "status_ready": "準備完了",
        "status_scanning": "先にファイルを表示し、フォルダーサイズをバックグラウンドで計算中...",
        "status_stopped": "停止しました",
        "status_done": "完了",
        "name": "名前",
        "type": "種類",
        "size": "サイズ",
        "modified": "更新日",
        "category": "カテゴリ",
        "full_path": "フルパス",
        "file": "ファイル",
        "folder": "フォルダー",
        "calculating": "計算中...",
        "error_path": "パスが存在しません。",
        "select_folder": "フォルダーを選択",
        "all_disk_hint": "ディスク全体をスキャンするには C:/ などのドライブ直下を指定してください。",
        "system": "システム",
        "launcher": "ランチャー",
        "game": "ゲーム",
        "cache": "キャッシュ / 一時ファイル",
        "user_files": "ユーザーファイル",
        "app_data": "アプリデータ",
        "development": "開発",
        "media": "メディア",
        "documents": "ドキュメント",
        "archives": "アーカイブ",
        "installers": "インストーラー",
        "programs": "プログラム / 実行ファイル",
        "other": "その他",
    },
}

SORT_KEYS = ["size", "modified", "name", "type", "category"]

SKIP_DIR_NAMES = {
    "system volume information",
    "$recycle.bin",
    "windows.old",
}
